# Generated by Django 3.0.7 on 2020-06-29 09:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Body', models.TextField()),
                ('Slug', models.SlugField(blank=True)),
                ('Likes', models.PositiveIntegerField(default=0)),
                ('Dislikes', models.PositiveIntegerField(default=0)),
                ('Date_added', models.DateField(default=datetime.date(2020, 6, 29))),
                ('Date_time_added', models.DateTimeField(default=datetime.datetime(2020, 6, 29, 9, 34, 49, 219003, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='post_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_comment', models.BooleanField(default=False)),
                ('Body', models.CharField(max_length=512)),
                ('Parent', models.IntegerField(blank=True, null=True, verbose_name='self')),
                ('Likes', models.PositiveIntegerField(default=0)),
                ('Dislikes', models.PositiveIntegerField(default=0)),
                ('Date_added', models.DateField(default=datetime.date(2020, 6, 29))),
                ('Date_time_added', models.DateTimeField(default=datetime.datetime(2020, 6, 29, 9, 34, 49, 218003, tzinfo=utc))),
            ],
        ),
    ]
