# Generated by Django 3.0.7 on 2020-06-30 09:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200629_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Date_added',
            field=models.DateField(default=datetime.date(2020, 6, 30)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Date_time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 9, 0, 48, 619987, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='Date_added',
            field=models.DateField(default=datetime.date(2020, 6, 30)),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='Date_time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 9, 0, 48, 618986, tzinfo=utc)),
        ),
    ]
