# Generated by Django 3.0.7 on 2020-06-30 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200630_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Date_time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 9, 9, 5, 314844, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='Date_time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 9, 9, 5, 313844, tzinfo=utc)),
        ),
    ]
