# Generated by Django 3.0.7 on 2020-07-08 06:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200630_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Date_added',
            field=models.DateField(default=datetime.date(2020, 7, 8)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Date_time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 6, 52, 19, 194616, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='Date_added',
            field=models.DateField(default=datetime.date(2020, 7, 8)),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='Date_time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 6, 52, 19, 194117, tzinfo=utc)),
        ),
    ]
