# Generated by Django 3.0.7 on 2020-07-12 07:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200708_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Date_added',
            field=models.DateField(default=datetime.date(2020, 7, 12)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Date_time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 7, 57, 42, 523475, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='Date_added',
            field=models.DateField(default=datetime.date(2020, 7, 12)),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='Date_time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 7, 57, 42, 522475, tzinfo=utc)),
        ),
    ]
