# Generated by Django 3.0.7 on 2020-07-14 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200712_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Date_added',
            field=models.DateField(default=datetime.date(2020, 7, 14)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Date_time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 14, 24, 25, 428367, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='Date_added',
            field=models.DateField(default=datetime.date(2020, 7, 14)),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='Date_time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 14, 24, 25, 427866, tzinfo=utc)),
        ),
    ]
