# Generated by Django 3.0.7 on 2020-07-14 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200714_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Date_time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 14, 26, 27, 377299, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='Date_time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 14, 26, 27, 376299, tzinfo=utc)),
        ),
    ]
