# Generated by Django 3.0.7 on 2020-06-20 13:29

import apps.articles.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdminComment', models.BooleanField(default=False)),
                ('Body', models.CharField(max_length=512)),
                ('Likes', models.PositiveIntegerField(default=0)),
                ('Dislikes', models.PositiveIntegerField(default=0)),
                ('DateAdded', models.DateField(default=datetime.date(2020, 6, 20))),
                ('DateTimeAdded', models.DateTimeField(default=datetime.datetime(2020, 6, 20, 13, 29, 31, 969684, tzinfo=utc))),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_comment_author', to=settings.AUTH_USER_MODEL)),
                ('Parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_set', to='articles.comment')),
            ],
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Thesis', models.CharField(blank=True, max_length=255, null=True)),
                ('Body', models.TextField()),
                ('Slug', models.SlugField(blank=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to=apps.articles.models.upload_location)),
                ('Likes', models.PositiveIntegerField(default=0)),
                ('Dislikes', models.PositiveIntegerField(default=0)),
                ('DateAdded', models.DateField(default=datetime.date(2020, 6, 20))),
                ('DateTimeAdded', models.DateTimeField(default=datetime.datetime(2020, 6, 20, 13, 29, 31, 970684, tzinfo=utc))),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Comments', models.ManyToManyField(blank=True, null=True, to='articles.comment')),
                ('Parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_set', to='articles.article')),
            ],
        ),
    ]
