# Generated by Django 3.0.7 on 2020-06-29 09:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200629_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='DateTimeAdded',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 9, 36, 39, 219999, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='Parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
        migrations.AlterField(
            model_name='article_comment',
            name='DateTimeAdded',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 9, 36, 39, 218999, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article_comment',
            name='Parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.article_comment'),
        ),
    ]
