# Generated by Django 3.0.7 on 2020-06-30 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200630_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='DateTimeAdded',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 9, 9, 5, 329380, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article_comment',
            name='DateTimeAdded',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 9, 9, 5, 328380, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='article_favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=120, null=True)),
                ('Favorite', models.ManyToManyField(blank=True, null=True, to='articles.article')),
            ],
        ),
    ]
