# Generated by Django 3.0.7 on 2020-07-08 06:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200630_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_favorite',
            name='Slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='DateAdded',
            field=models.DateField(default=datetime.date(2020, 7, 8)),
        ),
        migrations.AlterField(
            model_name='article',
            name='DateTimeAdded',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 6, 52, 19, 201117, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article_comment',
            name='DateAdded',
            field=models.DateField(default=datetime.date(2020, 7, 8)),
        ),
        migrations.AlterField(
            model_name='article_comment',
            name='DateTimeAdded',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 6, 52, 19, 200118, tzinfo=utc)),
        ),
    ]
