# Generated by Django 3.0.7 on 2020-07-12 07:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200708_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Category',
            field=models.CharField(blank=True, choices=[('Landscape', 'Пейзаж'), ('Art', 'Арт'), ('3D', '3D'), ('Photo', 'Фотография'), ('Portrait', 'Портрет')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='DateAdded',
            field=models.DateField(default=datetime.date(2020, 7, 12)),
        ),
        migrations.AlterField(
            model_name='article',
            name='DateTimeAdded',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 7, 57, 42, 527476, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article_comment',
            name='DateAdded',
            field=models.DateField(default=datetime.date(2020, 7, 12)),
        ),
        migrations.AlterField(
            model_name='article_comment',
            name='DateTimeAdded',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 7, 57, 42, 526475, tzinfo=utc)),
        ),
    ]
