# Generated by Django 3.0.7 on 2020-07-14 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200714_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Category',
            field=models.CharField(blank=True, choices=[('Landscape', 'Пейзаж'), ('Art', 'Арт'), ('Photo', 'Фотография'), ('3D', '3D'), ('Portrait', 'Портрет')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article_comment',
            name='DateTimeAdded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
