# Generated by Django 3.0.7 on 2020-06-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='Image',
        ),
    ]
