# Generated by Django 3.0.7 on 2020-06-29 09:27

import apps.arts.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=120, null=True)),
                ('Thesis', models.CharField(blank=True, max_length=512, null=True)),
                ('Slug', models.SlugField(blank=True)),
                ('Image', models.ImageField(upload_to=apps.arts.models.upload_location)),
                ('Likes', models.PositiveIntegerField(default=0)),
                ('Dislikes', models.PositiveIntegerField(default=0)),
                ('DateAdded', models.DateField(default=datetime.date(2020, 6, 29))),
                ('DateTimeAdded', models.DateTimeField(default=datetime.datetime(2020, 6, 29, 9, 27, 51, 854012, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdminComment', models.BooleanField(default=False)),
                ('Body', models.CharField(max_length=512)),
                ('Likes', models.PositiveIntegerField(default=0)),
                ('Dislikes', models.PositiveIntegerField(default=0)),
                ('DateAdded', models.DateField(default=datetime.date(2020, 6, 29))),
                ('DateTimeAdded', models.DateTimeField(default=datetime.datetime(2020, 6, 29, 9, 27, 51, 853011, tzinfo=utc))),
            ],
        ),
    ]
