# Generated by Django 3.0.7 on 2020-06-29 09:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0003_auto_20200629_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='DateTimeAdded',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 9, 36, 39, 225000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='DateTimeAdded',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 9, 36, 39, 224000, tzinfo=utc)),
        ),
    ]
