# Generated by Django 3.0.7 on 2020-06-30 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0005_auto_20200630_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='DateTimeAdded',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 9, 9, 5, 338380, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='art_comment',
            name='DateTimeAdded',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 9, 9, 5, 337381, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='art_favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=120, null=True)),
                ('Favorite', models.ManyToManyField(blank=True, null=True, to='arts.art')),
            ],
        ),
    ]
