# Generated by Django 3.0.7 on 2020-07-12 07:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0007_auto_20200708_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='DateAdded',
            field=models.DateField(default=datetime.date(2020, 7, 12)),
        ),
        migrations.AlterField(
            model_name='art',
            name='DateTimeAdded',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 7, 57, 42, 532977, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='art_comment',
            name='DateAdded',
            field=models.DateField(default=datetime.date(2020, 7, 12)),
        ),
        migrations.AlterField(
            model_name='art_comment',
            name='DateTimeAdded',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 7, 57, 42, 531977, tzinfo=utc)),
        ),
    ]
