# Generated by Django 3.0.7 on 2020-07-14 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0008_auto_20200712_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='DateAdded',
            field=models.DateField(default=datetime.date(2020, 7, 14)),
        ),
        migrations.AlterField(
            model_name='art',
            name='DateTimeAdded',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 14, 24, 25, 443368, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='art_comment',
            name='DateAdded',
            field=models.DateField(default=datetime.date(2020, 7, 14)),
        ),
        migrations.AlterField(
            model_name='art_comment',
            name='DateTimeAdded',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 14, 24, 25, 442368, tzinfo=utc)),
        ),
    ]
