# Generated by Django 3.0.7 on 2020-07-14 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0009_auto_20200714_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='DateTimeAdded',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 14, 26, 27, 392299, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='art_comment',
            name='DateTimeAdded',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 14, 26, 27, 391299, tzinfo=utc)),
        ),
    ]
